### PR TITLE
Volunteer Map

### PR DESCRIPTION
**Pull request by KohinaTheCat**
DEFAULT VIEW:
image

MARKER CLICK VIEW:
image

(press x on the tag to remove it)

ISSUE:
image

This happens because of `<Layout/>`. I tried to remove it and it makes the header disappear too which is super weird, so I left it as it is.

### CODE REVIEW

**Review by pablomdd — APPROVED** [review]
Looks good!

**Comment by pablomdd** [comment]
I think the Layout thing happens because it has a fix height

**Review by ShayanRiyaz — APPROVED** [review]
👍🏽

**Comment by KohinaTheCat** [comment]
> I think the Layout thing happens because it has a fix height

ohhh i think youre right

**Comment by KohinaTheCat** [comment]
> > I think the Layout thing happens because it has a fix height
> 
> ohhh i think youre right

i dont understand why `Header` disappears if i remove only `Layout` though

**Pull request merged**
